[project]
name = "vajra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arm-pyart>=2.3.0",
    "cdsapi>=0.7.7",
    "dask>=2024.1.0",
    "fastapi>=0.115.0",
    "h5py>=3.11.0",
    "imdlib>=0.1.22",
    "ipykernel>=6.29.0",
    "joblib>=1.4.0",
    "jupyter>=1.0.0",
    "matplotlib>=3.9.0",
    "netcdf4>=1.7.0",
    "onnxruntime>=1.18.0",
    "pillow>=10.4.0",
    "pydantic>=2.8.0",
    "pyproj>=3.6.0",
    "python-dotenv>=1.0.0",
    "rasterio>=1.3.10",
    "scikit-learn>=1.5.0",
    "torch>=2.2.0",
    "uvicorn>=0.30.0",
    "xarray>=2024.1.0",
    "xgboost>=2.0.0",
    "xradar>=0.6.0",
    "zarr>=2.18.0",
]
